seed: 1234

## Data
label_map: conf/map.yaml
tr_data: conf/train_data.scp
cv_data: conf/val_data.scp
paddng: null

num_workers: 4

## Model
type: MobileNet # the type of networks to train [ResNet50, MobileNet]
model_config:
  mode: transfer
  ckpt: /DKUdata/tangbl/courses/CS302_CV/final_project/src/ckpt/mobilenet_v2-b0353104.pth


## Training
weighted_loss: false

augmentation: null

epochs: 20 # Train for 10 epochs

batch_size: 16 # Dont matter here, as we will iterate data one by one

optim:
  type: Adam
  lr: 1.0e-3

log_inverval: 10

grad_clip: 5